title: TapData Community Documentation
logo: "/assets/favicon.png"
description: The Documentation site of TapData
url: "https://eshujiushiwo.github.io"
remote_theme: just-the-docs/just-the-docs
search_enabled: false
aux_links:
  "TapData on GitHub":
    - "//github.com/tapdata/tapdata"
aux_links_new_tab: true
